spring.application.name=usuario-api
server.port=8080

# H2 console
enable-console=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource
spring.datasource.url=jdbc:h2:mem:usuariosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ValidaciÃ³n contraseÃ±a (configurable)
regex.password=^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).{8,}$
regex.email=^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$

# JWT
token.secret=2FEC98AB8374D95DF7C72BB31A1185B9F0A4C517AD376F2194D3A9817AE246DDC4576EBAA7989DD4D826
token.expiration-ms=3600000

#spring.security.user.name=admin
#spring.security.user.password=admin

server.servlet.context-path=/crud-evaluacion
server.error.include-stacktrace=always
server.error.include-message=always
springdoc.swagger-ui.path=/swagger-ui.html
